extends "res://scripts/main.gd"
var checks: Array = []
var ending: String = ""
func _ready() -> void:
	super._ready()
	GameFlow.finished.connect(func(name: String,_message: String): ending=name)
	call_deferred("run_checks")
func check(name: String,passed: bool) -> void:
	checks.append({"check":name,"passed":passed})
	print("QA ",JSON.stringify(checks[-1]))
func frames(count: int = 5) -> void:
	for i: int in range(count): await get_tree().process_frame
func fresh(area: String = "reception") -> void:
	EndingUI._close_overlay()
	MenuUI.close_all()
	ExperienceUI.close()
	_new_game()
	SceneRouter.route_to(area)
	ending = ""
	await frames()
func act(id: String,item: String = "") -> void:
	GameFlow.perform(id,item)
func choose(id: String) -> void:
	DialogueUI._select(DialogueUI.current_dialogue_id,id)
func run_checks() -> void:
	await frames()
	check("initial_menu",not GameState.run_active)
	await fresh()
	act("reception_stairs")
	check("stairs_guard",GameState.current_area=="reception")
	SubareaManager._open_receptionist_dialogue()
	MenuUI.open_pause()
	var key: InputEventKey = InputEventKey.new()
	key.keycode = KEY_A
	key.pressed = true
	Input.parse_input_event(key)
	await frames()
	check("pause_keyboard_blocks_choice",not GameState.has_flag("identified"))
	choose("A")
	check("pause_direct_blocks_choice",not GameState.has_flag("identified"))
	key.pressed=false
	Input.parse_input_event(key)
	MenuUI.close_all()
	choose("A")
	check("identity_badge",GameState.has_item("visitor_badge"))
	act("security_desk")
	act("reception_stairs")
	await frames()
	check("reception_progress",GameState.current_area=="innovation")
	act("take_vr")
	act("innovation_exit")
	await frames()
	act("rogerio","visitor_badge")
	check("ti_wrong_item",not GameState.has_flag("boss_ti_done"))
	act("rogerio","vr_glasses")
	check("ti_vr_consumed",GameState.has_flag("boss_ti_done") and not GameState.has_item("vr_glasses"))
	act("ti_exit")
	choose("B")
	await frames()
	act("communication_printer")
	check("stamp_needs_cc",not GameState.has_item("executive_priority_stamp"))
	act("communication_board")
	act("communication_printer")
	act("communication_exit")
	choose("B")
	await frames()
	selected_item="executive_priority_stamp"
	SuppliesFlow._handle_action("stan")
	check("supplies_gate",GameState.has_flag("boss_supplies_done"))
	SuppliesFlow._handle_action("exit")
	choose("B")
	await frames()
	act("hall_stairs")
	check("hall_dependencies",GameState.current_area=="hall")
	act("hall_finance")
	await frames()
	act("finance_bruno")
	choose("A")
	act("finance_reimbursement")
	choose("B")
	check("finance_documents",GameState.has_item("third_party_proof") and GameState.has_item("fiscal_exception_protocol"))
	act("finance_back")
	act("hall_engineering")
	await frames()
	act("engineering_os")
	check("os_requires_vest",not GameState.has_item("work_order"))
	act("engineering_vest")
	act("engineering_os")
	act("engineering_back")
	act("hall_stairs")
	await frames()
	act("security_sonia","work_order")
	check("security_disguise_guard",not GameState.has_flag("boss_security_done"))
	MenuUI.open_inventory(false)
	MenuUI.inventory_selected_id="maintenance_vest"
	MenuUI._inventory_use_selected()
	check("inventory_vest",GameState.disguise=="maintenance")
	act("security_sonia","work_order")
	await frames()
	check("security_rh",GameState.current_area=="rh")
	act("rh_helena")
	act("rh_point")
	act("rh_parallel")
	act("rh_validator")
	act("rh_microwave")
	act("rh_helena")
	await frames()
	check("rh_signature",GameState.has_item("rh_validation_signature") and GameState.current_area=="documentation")
	act("documentation_exit")
	check("bolota_guard",GameState.current_area=="documentation")
	act("documentation_bolota")
	act("documentation_exit")
	await frames()
	act("legal_analysis","legal_bolota_pending")
	check("legal_five_requirements",not GameState.has_flag("boss_legal_done"))
	act("legal_phone")
	act("legal_phone")
	act("legal_analysis","legal_bolota_pending")
	await frames()
	check("bolota_replaced",GameState.has_item("legal_bolota_approved") and not GameState.has_item("legal_bolota_pending"))
	act("director_secretary")
	act("director_answer_correct")
	act("director_door")
	check("canonical_delivery",ending=="ENTREGA CONCLUÍDA")
	await persistence_checks()
	await content_checks()
	await geometry_checks()
	await input_checks()
	var file: FileAccess = FileAccess.open("res://qa/results.json",FileAccess.WRITE)
	file.store_string(JSON.stringify(checks,"\t"))
	file.close()
	MusicManager.player.stop()
	MusicManager.player.stream=null
	SFXManager.player.stop()
	SFXManager.player.stream=null
	OS.delay_msec(500)
	await frames()
	var failures: int = 0
	for row: Dictionary in checks:
		if not row["passed"]: failures+=1
	print("QA COMPLETE ",checks.size()," FAILED ",failures)
	get_tree().quit(1 if failures>0 else 0)
func persistence_checks() -> void:
	await fresh()
	PlayerController._image_position=Vector2(450,700)
	check("save_written",SaveManager.save_slot(95))
	PlayerController._image_position=Vector2(800,850)
	check("load_accepted",SaveManager.load_slot(95))
	await frames()
	check("position_restored",PlayerController._image_position.distance_to(Vector2(450,700))<0.01)
	GameState.set_flag("backup_marker","first")
	SaveManager.save_slot(95)
	GameState.set_flag("backup_marker","second")
	SaveManager.save_slot(95)
	var file: FileAccess = FileAccess.open("user://save_95.json",FileAccess.WRITE)
	file.store_string("{truncated")
	file.close()
	check("backup_recovers",SaveManager.load_slot(95) and GameState.flags.get("backup_marker")=="first")
	await frames()
	var valid: Dictionary = {"version":2,"state":GameState.to_dict(),"player":PlayerController.snapshot(),"dialogue":{}}
	for change: Array in [["version",999],["state",{"current_area":"invalid"}],["player",{"area":"reception","position":[0,"bad"]}],["dialogue",{"choices":"bad"}]]:
		var invalid: Dictionary = valid.duplicate(true)
		invalid[change[0]]=change[1]
		check("reject_"+change[0],not SaveManager._valid_payload(invalid))
	var legacy: Dictionary=valid.duplicate(true)
	legacy["version"]=1
	legacy.erase("player")
	legacy.erase("dialogue")
	check("legacy_v1",SaveManager._valid_payload(legacy))
	SubareaManager._open_receptionist_dialogue()
	check("dialogue_save",SaveManager.save_slot(96))
	DialogueUI.close_dialogue()
	SaveManager.load_slot(96)
	await frames()
	check("dialogue_restored",DialogueUI.current_dialogue_id=="receptionist_intro")
	DialogueUI.close_dialogue()
	DialogueUI.show_speech("Teste","Esta fala deve permanecer disponível durante a pausa.")
	MenuUI.open_pause()
	var remaining: float=DialogueUI.speech_remaining
	await frames(20)
	check("speech_pause",is_equal_approx(remaining,DialogueUI.speech_remaining))
	MenuUI.close_all()
	SettingsManager.set_value("manual_dialogue",true)
	await frames(20)
	check("manual_speech",DialogueUI.speech_layer!=null)
	SettingsManager.set_value("manual_dialogue",false)
	DialogueUI.close_speech()
	MenuUI.inventory_selected_id="vr_glasses"
	MenuUI.open_inventory()
	check("stale_item_cleared",MenuUI.inventory_selected_id=="" or GameState.has_item(MenuUI.inventory_selected_id))
	MenuUI.close_all()
	ExperienceUI.open_journal()
	check("journal_modal",ExperienceUI.is_open() and InteractionGuard.modal_blocked())
	ExperienceUI.close()
	SettingsManager.set_value("font_scale",1.3)
	check("font_scale",SettingsManager.font_size(20)==26)
	SettingsManager.set_value("font_scale",1.0)
	check("music_resource",ResourceLoader.exists(MusicManager.INNOVATION_TI_AUDIO_PATH))
	SaveManager.delete_slot(95)
	SaveManager.delete_slot(96)
func content_checks() -> void:
	var terminal_cases: Array = [["reception","reception_insist_security","PIZZA APREENDIDA"],["reception","reception_insist_stairs","ACESSO NÃO AUTORIZADO"],["innovation_meeting_room","innovation_meeting","INOVAÇÃO DEMAIS"],["ti","ti_weekly","REUNIÃO RECORRENTE"],["ti_service_desk","ti_service","ENTREGA DIGITALMENTE CONCLUÍDA"],["ti_server_room","ti_security","INCIDENTE DE SEGURANÇA"],["ti_systems_room","ti_virtualize","PIZZA AS A SERVICE"],["engineering","engineering_analysis","FALHA ESTRUTURAL"],["security","security_access","ÁREA RESTRITA"],["security","security_inspection","PIZZA EM QUARENTENA"],["rh","rh_collaboration","DEMITIDO ANTES DE SER CONTRATADO"],["rh_third_party_registration","rh_employee","EFETIVADO POR ENGANO"],["legal","legal_terms","LI E ACEITO"]]
	for entry: Array in terminal_cases:
		await fresh(entry[0])
		ContentFlow.open_action(entry[1])
		choose("A")
		check("ending_"+entry[2],ending==entry[2])
	await fresh("finance")
	act("finance_bruno")
	choose("C")
	check("ending_PROMOVIDO",ending=="PROMOVIDO A TERCEIRIZADO")
	await fresh("finance")
	act("finance_reimbursement")
	choose("C")
	check("ending_CUSTODIA",ending=="PIZZA SOB CUSTÓDIA FISCAL")
	await fresh("legal")
	act("legal_secretary")
	choose("B")
	check("ending_EM_ANALISE",ending=="EM ANÁLISE")
	await fresh("supplies")
	for entry: Array in [["quotes","A","MENOR PREÇO"],["warehouse","A","MATERIAL RETIDO"],["supplier","A","FORNECEDOR HOMOLOGADO"],["supplier","D","CADASTRO EM ANÁLISE"]]:
		await fresh("supplies")
		SuppliesFlow._handle_action(entry[0])
		choose(entry[1])
		check("ending_"+entry[2],ending==entry[2])
	await fresh()
	act("reception_exit")
	check("ending_ABANDONADA",ending=="ENTREGA ABANDONADA")
	await fresh()
	SubareaManager._open_receptionist_dialogue()
	choose("C")
	check("ending_DESTINO",ending=="DESTINO NÃO ENCONTRADO")
	await fresh("reception_waiting_room")
	for i: int in range(4): SubareaManager._show_waiting_visitor_dialogue()
	choose("C")
	check("ending_VISITANTE",ending=="VISITANTE RETIRADO")
	await fresh("reception_auditorium")
	SubareaManager._open_auditorium_dialogue()
	choose("B")
	check("ending_IDENTIDADE",ending=="IDENTIDADE FALSIFICADA")
	await fresh("innovation")
	for i: int in range(3): act("innovation_bathroom")
	check("ending_ENCANAMENTO",ending=="ENTREGA POR ENCANAMENTO")
	await fresh("directorate")
	for i: int in range(3): act("director_answer_wrong")
	check("ending_DIRETOR",ending=="DIRETOR DESCONHECIDO")
	await fresh("directorate")
	GameState.pizza["temperature"]=0
	GameFlow._resolve_delivery()
	check("ending_FRIA",ending=="PIZZA FRIA")
	await fresh("directorate")
	GameState.pizza["elapsed_minutes"]=150
	GameFlow._resolve_delivery()
	check("ending_ATRASO",ending=="ENTREGA TARDE DEMAIS")
	await fresh("directorate")
	GameState.pizza["quantity"]=0
	GameState.pizza["integrity"]=0
	GameFlow._resolve_delivery()
	check("ending_SEM_PIZZA",ending=="SEM PIZZA")
	check("all_30_endings",EndingManager.seen.size()==30)
	await fresh("reception_auditorium")
	SubareaManager._open_auditorium_dialogue()
	choose("A")
	await frames()
	check("shortcut_rh",GameState.current_area=="rh" and GameState.has_flag("temporary_rh_shortcut"))
	act("rh_back")
	check("shortcut_return",GameState.current_area=="reception")
	await fresh("reception_auditorium")
	SubareaManager._open_auditorium_dialogue()
	choose("C")
	await fresh("hall")
	act("hall_map")
	act("hall_wait")
	GameState.set_flag("finance_done")
	act("hall_wait")
	await fresh("finance")
	act("finance_calculator")
	await fresh("security")
	for i: int in range(3): act("security_monitors")
	check("all_22_achievements",AchievementManager.unlocked_names.size()==22)
	await fresh("innovation_meeting_room")
	ContentFlow.open_action("innovation_meeting")
	choose("B")
	SceneRouter.route_to("rh")
	await frames()
	act("rh_helena")
	check("collaboration_consequence",DialogueUI.current_dialogue_id=="content_rh_collaboration")
	choose("C")
	check("collaboration_resolved",GameState.has_flag("collaboration_resolved"))
	await fresh("legal")
	GameState.add_item("legal_bolota_approved")
	GameState.set_flag("boss_legal_done")
	act("legal_back")
	act("documentation_exit")
	act("legal_analysis")
	check("bolota_backtracking",GameState.current_area=="directorate" and not GameState.has_item("legal_bolota_pending"))
	await fresh()
	ContentFlow.open_action("reception_insist_security")
	choose("A")
	check("checkpoint_available",SaveManager.has_slot(0))
	check("checkpoint_load",SaveManager.load_slot(0))
	await frames()
	check("checkpoint_choice_restored",GameState.run_active and DialogueUI.current_dialogue_id=="content_reception_insist_security")
func geometry_checks() -> void:
	var Hotspots = preload("res://scripts/hotspot_catalog.gd")
	var Walkable = preload("res://scripts/walkable_catalog.gd")
	for area: String in Hotspots.BACKGROUNDS:
		if area=="menu": continue
		await fresh(area)
		check("area_"+area,ResourceLoader.exists(Hotspots.BACKGROUNDS[area]))
		var valid: bool=true
		for hs: Dictionary in Hotspots.get_hotspots(area):
			var r: Array=hs["rect"]
			valid=valid and r[0]>=0 and r[1]>=0 and r[0]+r[2]<=1672 and r[1]+r[3]<=941
		check("bounds_"+area,valid)
		var floor_rect: Rect2=Walkable.bounds(area)
		var path: PackedVector2Array=Walkable.path(area,floor_rect.position+Vector2(10,10),floor_rect.end-Vector2(10,10))
		valid=not path.is_empty()
		for i: int in range(path.size()-1): valid=valid and Walkable.clear_segment(area,path[i],path[i+1])
		check("walk_"+area,valid)
	await fresh()
	var world_button: Button=null
	for child: Node in get_children():
		if child is Button and child.get_meta("world_hotspot",false):
			world_button=child
			break
	check("keyboard_world_focus",world_button!=null and world_button.focus_mode==Control.FOCUS_ALL)
	MenuUI.open_pause()
	await frames()
	check("keyboard_modal_blocks_world",world_button.focus_mode==Control.FOCUS_NONE)
	MenuUI.close_all()

func input_checks() -> void:
	await fresh()
	SettingsManager.set_value("reduced_motion",true)
	var receptionist: Button=null
	for child: Node in get_children():
		if child is Button and child.get_meta("world_hotspot",false) and child.tooltip_text=="Balcão da Recepção": receptionist=child
	check("reception_button_available",receptionist!=null)
	if receptionist!=null:
		receptionist.grab_focus()
		var key: InputEventKey=InputEventKey.new()
		key.keycode=KEY_ENTER
		key.pressed=true
		Input.parse_input_event(key)
		await frames(2)
		key.pressed=false
		Input.parse_input_event(key)
		await frames()
		check("keyboard_opens_reception_dialogue",DialogueUI.current_dialogue_id=="receptionist_intro")
		choose("A")
		check("keyboard_dialogue_progress",GameState.has_flag("identified"))
	await fresh()
	var label: String="Balcão da Recepção"
	var button: Button=null
	for child: Node in get_children():
		if child is Button and child.get_meta("world_hotspot",false) and child.tooltip_text==label: button=child
	if button!=null:
		var point: Vector2=button.global_position+button.size*0.5
		var motion: InputEventMouseMotion=InputEventMouseMotion.new()
		motion.position=point
		motion.global_position=point
		get_viewport().push_input(motion,true)
		await frames(2)
		var mouse: InputEventMouseButton=InputEventMouseButton.new()
		mouse.position=point
		mouse.global_position=point
		mouse.button_index=MOUSE_BUTTON_LEFT
		mouse.pressed=true
		get_viewport().push_input(mouse,true)
		await frames(2)
		mouse.pressed=false
		get_viewport().push_input(mouse,true)
		await frames()
		check("mouse_opens_reception_dialogue",DialogueUI.current_dialogue_id=="receptionist_intro")
	SettingsManager.set_value("reduced_motion",false)
